List<String> quotes = [
  ("The secret of getting ahead is getting started"),
  ("It's hard to beat a person who never gives up"),
  ("Do one thing everyday that scares you"),
  ("Impossible is just an opinion"),
  ("The hard days are what make you stronger"),
  ("If opportunity doesn’t knock, build a door"),
  ("Work hard in silence, let your success be the noise"),
  ("Work hard and amazing things will happen"),
  ("Nothing will work unless you do"),
  ("In the middle of every difficulty lies opportunity"),
  ("Go the extra mile. It’s never crowded there"),
  ("Turn your wounds into wisdom"),
  ("Begin anywhere"),
  ("Make each day your masterpiece"),
  ("Doubt kills more dreams than failure ever will"),
  ("You must do the thing you think you cannot do"),
  ("Focus on being productive instead of busy"),
  ("It’s never too late to be what you might’ve been"),
  ("You can do anything you set your mind to"),
  ("You never know what you can do until you try"),
  ("A goal is a dream with a deadline"),
];